# Solución práctica


## Carga de datos

```{r}
library(tidyverse)

```


**Tomo 1**


```{r}
dir("raw_text", pattern = "tomo1")
```

```{r}
#página por linea
tomo1 <- read_csv("raw_text/rondalles_ocr_tomo1.csv")
# indice
tabla1 <- read_csv("raw_text/tabla_tomo1.csv")
```


```{r}
t2=tabla1[-c(1:3),]
t2$final=c(t2$indice[-1]-1,300)
knitr::kable(t2)
```



```{r}
titulo=t2$titulo
length(titulo)

extrae <- function(i) {
  tomo1 %>%
    filter(pagina >= t2$indice[i] & pagina <= t2$final[i]) %>%
    pull(texto) %>%
    paste(collapse = "\n")}

sapply(1:length(titulo), extrae)-> rondallas
corpus1=tibble(titulo,rondallas)
corpus1
```

Tomo 2 (repetir lecto 1913)


Tomo 3 


```{r}
tomo3=read_csv("raw_text/rondalles_ocr_tomo3.csv")
tabla3=read_csv("raw_text/tabla_tomo3.csv")
tabla3$indice=tabla3$pagina+10
n=dim(tomo3)[1]
tabla3$final=c(tabla3$indice[-1]-1,n)


extrae <- function(i) {
  tomo3 %>%
    filter(pagina >= t2$indice[i] & pagina <= t2$final[i]) %>%
    pull(texto) %>%
    paste(collapse = "\n")}

sapply(1:length(titulo), extrae)-> rondallas
corpus3=tibble(titulo,rondallas)
corpus3
```

